version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - ruby/install-deps
      # Store bundle cache
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
  test:
    docker:
      - image: cimg/ruby:2.7-node
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: rails_blog_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci-demo-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      #- ruby/rspec-test
      - run:
          name: Run Rspec and automatically bisect on failure
          command: |
            TEST_RUN=$(bundle exec rspec --order random --failure-exit-code 0)
            echo "export TEST_RESULTS=$TEST_RUN" >> $BASH_ENV
            STATUS=$(echo $TEST_RUN | grep -cw "0 failures")
            SEED=$(echo $TEST_RUN | sed -n -e 's/^.*seed //p')
            echo $STATUS
            echo $SEED

            echo "finally done, checking if bisect is needed"
            if [[ "$STATUS" == "1" ]]; then
              echo "Proceeding with build, no failures"
              exit 0
            else
              echo "Failure present, re-running with bisect"
              bundle exec rspec --format progress --seed ${SEED} --bisect
            fi
      - run:
          name: Run Rspec Bisect on failure
          when: on_fail
          command: |
            if [ -n "$TEST_RESULTS" ]; then
              STATUS=$(echo $TEST_RUN | grep -cw "0 failures")
              SEED=$(echo $TEST_RUN | sed -n -e 's/^.*seed //p')
              echo $STATUS
              echo $SEED
            else
              echo "Rspec step not run, no bisect needed"
            fi
      #- ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
