version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - ruby/install-deps
      # Store bundle cache
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
  test:
    docker:
      - image: cimg/ruby:2.7-node
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: rails_blog_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci-demo-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      #- ruby/rspec-test
      - run:
          name: Run Rspec and automatically bisect on failure
          command: |
            touch test-results.txt
            exec &> >(tee -a test-results.txt) | bundle exec rspec --order random 
      - run:
          name: Run Rspec Bisect on failure
          when: on_fail
          command: |
            if [ -s test-results.txt ]; then
              SEED=$(cat test-results.txt | sed -n -e 's/^.*seed //p' | head -1)
              echo $SEED
              bundle exec rspec --format progress --seed ${SEED} --bisect
            else
              echo "Rspec step not run, no bisect needed"
            fi
      #- ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
